import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import { UserSyncProvider } from "@/components/user-sync-provider";
import { Toaster } from "sonner";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (

    <ClerkProvider>
      <TRPCReactProvider>
        <html lang="en" className={`${geist.variable}`}>
          <body>
            <UserSyncProvider>
              <header className="flex justify-end items-center p-4 gap-4 h-16">
                <Link href="/" className="text-xl sm:text-2xl font-extrabold tracking-tight">
                  <span className="text-[#6c47ff]">Catalysts</span>
                </Link>
                <SignedOut>
                  <SignInButton />
                  <SignUpButton>
                    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                      Sign Up
                    </button>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </header>
              {children}
              <Toaster />
            </UserSyncProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
