import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import Link from "next/link";
import { UserSyncProvider } from "@/components/user-sync-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (

    <ClerkProvider>
      <TRPCReactProvider>
        <html lang="en" className={`${geist.variable}`}>
          <body>
            <UserSyncProvider>
              <header className="flex items-center justify-between px-4 sm:px-6 py-3 border-b border-white/10">
                <Link href="/" className="text-xl sm:text-2xl font-extrabold tracking-tight">
                  <span className="text-[#6c47ff]">Catalysts</span>
                </Link>
                <div className="flex items-center gap-3">
                  <SignedOut>
                    <SignInButton>
                      <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-9 sm:h-10 px-4 sm:px-5 cursor-pointer">
                        Sign In
                      </button>
                    </SignInButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </header>
              {children}
              <Toaster />
            </UserSyncProvider>
          </body>
        </html>
      </TRPCReactProvider>
    </ClerkProvider>
  );
}
